version: '3.8'

services:
    db:
        image: postgres:16.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=zadier
            - POSTGRES_PASSWORD=dQw4w9WgXcQ
            - POSTGRES_DB=zadier
        volumes:
            - ./db:/var/lib/postgresql/data
